- hosts: all
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes
    - name: Install packages
      apt:
        pkg:
          - vim
          - zsh
          - git
          - tmux
          - tree
          - htop
          - nmap
          - net-tools
    - name: apt upgrade
      apt:
        upgrade: full
    - name: apt autoclean
      apt:
        autoclean: yes
    # If you want to chsh zsh in raspberry pi os, you should comment out pam_shells.so.
    - name: Comment out pam_shells.so
      lineinfile:
        dest: /etc/pam.d/chsh
        state: present
        backup: true
        regexp: '^auth.*required.*pam_shells.so'
        line: '#auth required pam_shells.so'
    - name: Change shell to zsh
      shell: sudo chsh -s /usr/bin/zsh {{ ansible_ssh_user }}
    - name: Permit root command to logined ssh user
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        backup: true
        regexp: '^#PermitRootLogin.*'
        line: 'PermitRootLogin forced-commands-only'
    - name: Change theme to alanpeabody
      lineinfile:
        dest: $HOME/.zshrc
        state: present
        backup: true
        regexp: '^ZSH_THEME="robbyrussell"'
        line: 'ZSH_THEME="alanpeabody"'
      become: false



